#!/bin/bash

# Directory where you copied the .tar.gz files on the new machine.
# IMPORTANT: Update this path if you placed them somewhere else!
SOURCE_DIR="/media/bemunin/nv-fti-course/ros-docker-images"

# The expected compressed image files generated by the save script
FILES=(
    "nv_fti_ros_humble__latest.tar.gz"
    "isaac_sim_ros__ubuntu_22_humble.tar.gz"
)

echo "Starting Docker image import..."
echo "Checking source directory: $SOURCE_DIR"
echo "-----------------------------------"

# 1. Verify the directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "❌ Error: Directory $SOURCE_DIR does not exist."
    echo "Please open this script and update the SOURCE_DIR variable to point to where you saved the files."
    exit 1
fi

# 2. Loop through and load each file
for FILE in "${FILES[@]}"; do
    FULL_PATH="${SOURCE_DIR}/${FILE}"
    
    echo "Loading $FILE..."
    
    # Check if the specific file exists before trying to load
    if [ ! -f "$FULL_PATH" ]; then
        echo "⚠️  Warning: File not found at $FULL_PATH. Skipping."
        echo "-----------------------------------"
        continue
    fi

    # Execute the docker load command
    docker load -i "$FULL_PATH"

    # Check if the command was successful
    if [ $? -eq 0 ]; then
        echo "✅ Successfully loaded: $FILE"
    else
        echo "❌ Failed to load $FILE. You may need to run this script with 'sudo'."
    fi
    echo "-----------------------------------"
done

echo "Import process finished!"
echo "Run 'docker images' to verify they are ready to use."